/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheInnerCircleRouteImport } from './routes/the-inner-circle'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MembershipBenefitsRouteImport } from './routes/membership-benefits'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BlogsPostIdRouteImport } from './routes/blogs.$postId'

const TheInnerCircleRoute = TheInnerCircleRouteImport.update({
  id: '/the-inner-circle',
  path: '/the-inner-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipBenefitsRoute = MembershipBenefitsRouteImport.update({
  id: '/membership-benefits',
  path: '/membership-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogsPostIdRoute = BlogsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/membership-benefits': typeof MembershipBenefitsRoute
  '/services': typeof ServicesRouteWithChildren
  '/the-inner-circle': typeof TheInnerCircleRoute
  '/blogs/$postId': typeof BlogsPostIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/membership-benefits': typeof MembershipBenefitsRoute
  '/the-inner-circle': typeof TheInnerCircleRoute
  '/blogs/$postId': typeof BlogsPostIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/membership-benefits': typeof MembershipBenefitsRoute
  '/services': typeof ServicesRouteWithChildren
  '/the-inner-circle': typeof TheInnerCircleRoute
  '/blogs/$postId': typeof BlogsPostIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/calculators'
    | '/contact'
    | '/membership-benefits'
    | '/services'
    | '/the-inner-circle'
    | '/blogs/$postId'
    | '/services/$slug'
    | '/blogs/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/membership-benefits'
    | '/the-inner-circle'
    | '/blogs/$postId'
    | '/services/$slug'
    | '/blogs'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/calculators'
    | '/contact'
    | '/membership-benefits'
    | '/services'
    | '/the-inner-circle'
    | '/blogs/$postId'
    | '/services/$slug'
    | '/blogs/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  CalculatorsRoute: typeof CalculatorsRoute
  ContactRoute: typeof ContactRoute
  MembershipBenefitsRoute: typeof MembershipBenefitsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TheInnerCircleRoute: typeof TheInnerCircleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-inner-circle': {
      id: '/the-inner-circle'
      path: '/the-inner-circle'
      fullPath: '/the-inner-circle'
      preLoaderRoute: typeof TheInnerCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-benefits': {
      id: '/membership-benefits'
      path: '/membership-benefits'
      fullPath: '/membership-benefits'
      preLoaderRoute: typeof MembershipBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blogs/$postId': {
      id: '/blogs/$postId'
      path: '/$postId'
      fullPath: '/blogs/$postId'
      preLoaderRoute: typeof BlogsPostIdRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsPostIdRoute: typeof BlogsPostIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsPostIdRoute: BlogsPostIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRouteWithChildren,
  CalculatorsRoute: CalculatorsRoute,
  ContactRoute: ContactRoute,
  MembershipBenefitsRoute: MembershipBenefitsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TheInnerCircleRoute: TheInnerCircleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
